### ISSUE TITLE
NoClassDefFoundError: com/sun/javafx/css/parser/CSSParser running in JDK9

### ISSUE THREAD

**Issue by fvogler** [TweetWallFX/TweetwallFX#169]
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/javafx/css/parser/CSSParser
	at de.jensd.fx.glyphs.GlyphIcon.<clinit>(GlyphIcon.java:49)
	at org.tweetwallfx.controls.steps.CloudToTweetStep.createInfoBox(CloudToTweetStep.java:299)
	at org.tweetwallfx.controls.steps.CloudToTweetStep.doStep(CloudToTweetStep.java:160)
	at org.tweetwallfx.controls.stepengine.StepEngine.lambda$process$1(StepEngine.java:108)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.parser.CSSParser
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)

**Comment by svenreimers** [comment]
This can be easily fixed by upgrading to latest FontawesomeFX library

**Comment by jakin6** [comment]
The same issue ,i am using fontawesome 8.9 (which is the latest version ) with jdk 17 and javafx 17. It doesn't fix it

**Comment by maroua2benali** [comment]
i have the same problem

**Comment by NganeEmmanuel** [comment]
I solved my issue by using this version of the dependency  -- [https://mvnrepository.com/artifact/de.jensd/fontawesomefx-fontawesome/4.7.0-9.1.2](https://mvnrepository.com/artifact/de.jensd/fontawesomefx-fontawesome/4.7.0-9.1.2)

**Comment by Ducinviciable** [comment]
Thank it work for me

**Comment by Ducinviciable** [comment]
> I solved my issue by using this version of the dependency -- https://mvnrepository.com/artifact/de.jensd/fontawesomefx-fontawesome/4.7.0-9.1.2
thnk @NganeEmmanuel  it work for me. Thank you so much <3
